### ISSUE TITLE
[Landing Page] Sections 

### ISSUE THREAD

**Issue by ekapassa** [UNIC-IFF/BBF-FLASK-API#35]
We need to be consistent in the following aspects:

1. Each Section should be in a dedicated `<section>` element. This would allow us to have different colors in each section. Τhe section-color should change alternately (`is-medium` and `is-darkest`)
2. The spacing between the start/end of the section and the divider-title should be the same is all `<sections>`. Use the following screenshot as a reference
3. Dividers: All titles in each section should have a divider. Also, the spacing between the divider and the title should always be the same.  Use the following screenshot as a reference

![image](https://user-images.githubusercontent.com/15989176/178697846-d39ed623-c760-4e34-b006-33dafaf92311.png)

**Comment by gmixoulis** [comment]
check it if it ok, else lets discuss it over call
