### ISSUE TITLE
[Landing Page] Controller Figure

### ISSUE THREAD

**Issue by ekapassa** [UNIC-IFF/BBF-FLASK-API#8]
Move the controller figure (svg) at the top of the page (on top of the sponsors topic)

**Comment by gmixoulis** [comment]
I think sponsors should be included in the first view of the landing page, and then comes the controller figure.

**Comment by ekapassa** [comment]
@gmixoulis I would prefer to have the controller figure at the very top. This should be the entry point and this is what matters. It provides the whole view to the user. Currently, the figure that is provided at the very top, does not provide value to the user and it is not directly related to what we provide. This is why I propose to be replaced with the "controller" figure.

Check example below:
![image](https://user-images.githubusercontent.com/15989176/177955639-7885f32d-c61d-42b9-98b3-a623a2695184.png)
